/// Generates Swift source that embeds checked-in wb skill files into the release binary.
import Foundation

enum EmbeddedSkillGenerator {
	static func run() throws {
		let arguments = CommandLine.arguments
		guard arguments.count == 4 else {
			throw GeneratorError.message(
				"usage: EmbeddedSkillGenerator <SKILL.md> <install.sh> <output.swift>"
			)
		}

		let skillText = try readEmbeddedText(at: arguments[1])
		let installScriptText = try readEmbeddedText(at: arguments[2])
		let outputPath = arguments[3]
		let output = generatedSource(
			skillText: skillText,
			installScriptText: installScriptText
		)

		let outputURL = URL(fileURLWithPath: outputPath)
		try FileManager.default.createDirectory(
			at: outputURL.deletingLastPathComponent(),
			withIntermediateDirectories: true
		)
		try output.write(to: outputURL, atomically: true, encoding: .utf8)
	}

	private static func readEmbeddedText(at path: String) throws -> String {
		let text = try String(contentsOfFile: path, encoding: .utf8)
		if text.hasSuffix("\n") {
			return String(text.dropLast())
		}
		return text
	}

	private static func generatedSource(skillText: String, installScriptText: String) -> String {
		"""
		/// Generated by EmbeddedSkillPlugin from skill/SKILL.md and skill/install.sh.
		enum EmbeddedSkillPayload {
		\tstatic let skillText = \(rawMultilineLiteral(skillText))

		\tstatic let installScriptText = \(rawMultilineLiteral(installScriptText))
		}
		"""
	}

	private static func rawMultilineLiteral(_ text: String) -> String {
		let delimiter = String(repeating: "#", count: delimiterHashCount(for: text))
		return "\(delimiter)\"\"\"\n\(text)\n\"\"\"\(delimiter)"
	}

	private static func delimiterHashCount(for text: String) -> Int {
		var count = 1
		var searchRange = text.startIndex..<text.endIndex

		while let range = text.range(of: "\"\"\"", range: searchRange) {
			var hashCount = 0
			var index = range.upperBound
			while index < text.endIndex && text[index] == "#" {
				hashCount += 1
				index = text.index(after: index)
			}
			count = max(count, hashCount + 1)
			searchRange = range.upperBound..<text.endIndex
		}

		return count
	}
}

enum GeneratorError: LocalizedError {
	case message(String)

	var errorDescription: String? {
		switch self {
		case .message(let message):
			return message
		}
	}
}

do {
	try EmbeddedSkillGenerator.run()
} catch {
	FileHandle.standardError.write(Data("error: \(error.localizedDescription)\n".utf8))
	exit(1)
}
