name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  macos:
    name: Swift tests (macOS)
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Run tests
        run: ./test.sh
